name: swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v2
      - name: Build and Test
        run:  xcodebuild test -scheme Jolt -destination 'platform=iOS Simulator,OS=latest,name=iPhone 12' -enableCodeCoverage YES build test
